import React from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight } from 'lucide-react';
import { articles } from '../data/articles';
import EditorialVisual from '../components/EditorialVisual';
import Reveal from '../components/Reveal';

const kindFor=(c:string)=>c==='Ingredients'?'ingredient':c==='Routines'?'bath':c==='Baby Skin'?'baby':'journal';
export default function Blog(){
 const featured=articles[0], picks=articles.slice(1,4), skin=articles.filter(a=>a.category==='Baby Skin').slice(0,4), ing=articles.filter(a=>a.category==='Ingredients').slice(0,4), routines=articles.filter(a=>a.category==='Routines').slice(0,4), parent=articles.filter(a=>a.category==='Parent Guides').slice(0,4);
 return <div className="bg-ivory min-h-screen pt-32 pb-24"><div className="max-w-[1440px] mx-auto px-4 sm:px-6 lg:px-12">
  <Reveal className="max-w-4xl mb-14"><span className="text-sage font-semibold tracking-[.2em] uppercase text-xs mb-5 block">Kin & Clear Journal</span><h1 className="text-fluid-h1 mb-5">Thoughtful reads for the questions, routines and little discoveries of caring for new skin.</h1><p className="text-fluid-body-lg text-slate max-w-2xl">Editorial guides designed to make the complicated parts feel clearer.</p></Reveal>
  {featured&&<Reveal className="mb-28"><Link to={`/article/${featured.slug}`} className="group grid lg:grid-cols-12 gap-8 lg:gap-14 items-stretch border-y border-sage-light py-8 lg:py-10"><div className="lg:col-span-7 overflow-hidden rounded-[22px]"><EditorialVisual kind={kindFor(featured.category)} title={featured.title} className="aspect-[16/10] transition-transform duration-700 group-hover:scale-[1.015]"/></div><div className="lg:col-span-5 flex flex-col justify-center py-3"><span className="text-sage text-xs uppercase tracking-[.2em] font-semibold mb-4">Featured / {featured.category}</span><h2 className="font-serif text-[clamp(2.2rem,4vw,4.5rem)] leading-[1.04] mb-6 group-hover:text-sage transition-colors">{featured.title}</h2><p className="text-slate text-lg leading-relaxed mb-8">{featured.excerpt}</p><div className="flex items-center gap-4 text-sm"><span className="font-medium link-underline pb-1">Read story</span><span className="text-slate">{featured.readTime}</span></div></div></Link></Reveal>}

  <section className="mb-28"><div className="flex justify-between items-end mb-8"><div><span className="text-xs uppercase tracking-[.2em] text-slate">Selected reading</span><h2 className="font-serif text-4xl mt-2">Editor's Picks</h2></div></div><div className="grid lg:grid-cols-2 gap-6">{picks.map((a,i)=><Reveal key={a.id} className={i===0?'lg:row-span-2':''}><Link to={`/article/${a.slug}`} className="group block h-full border border-sage-light bg-white rounded-[22px] overflow-hidden"><EditorialVisual kind={kindFor(a.category)} title={a.title} className={i===0?'aspect-[16/11]':'aspect-[16/7]'}/><div className="p-7"><span className="text-xs uppercase tracking-[.18em] text-sage">{a.category}</span><h3 className={`font-serif mt-2 mb-3 group-hover:text-sage transition-colors ${i===0?'text-3xl':'text-2xl'}`}>{a.title}</h3><p className="text-slate line-clamp-2">{a.excerpt}</p></div></Link></Reveal>)}</div></section>

  <EditorialSection title="Baby Skin" intro="Barrier basics, dryness and the small changes parents notice first." items={skin}/>
  <section className="my-28 bg-sage-light rounded-[28px] p-10 lg:p-16 grid lg:grid-cols-2 gap-10 items-center"><div><span className="text-xs uppercase tracking-[.2em] text-sage font-semibold">Editorial note</span><h2 className="text-fluid-h2 mt-3 mb-5">Small guidance for the big firsts.</h2><p className="text-slate text-lg">No panic, no chemistry theatre — just clear explanations you can return to when a question comes up.</p></div><form className="flex flex-col sm:flex-row gap-2" onSubmit={e=>e.preventDefault()}><input className="flex-1 rounded-full px-6 py-4 bg-white border border-white focus:border-sage" placeholder="Your email address" type="email"/><button className="rounded-full px-7 py-4 bg-charcoal text-ivory hover:bg-sage transition-colors">Join the notes</button></form></section>
  <div className="grid lg:grid-cols-2 gap-16 lg:gap-24 mb-28"><CompactList title="Ingredient Deep Dives" items={ing}/><CompactList title="Routines & Care" items={routines}/></div>
  {parent.length>0&&<EditorialSection title="New Parent Notes" intro="Practical context for choosing less, understanding more and building a routine that feels manageable." items={parent}/>} 
  <section className="border-t border-sage-light pt-10"><div className="grid lg:grid-cols-[1fr_2fr] gap-8"><div><span className="text-xs uppercase tracking-[.2em] text-slate">Most read</span><h2 className="font-serif text-4xl mt-2">Start here</h2></div><div>{articles.slice(0,5).map((a,i)=><Link to={`/article/${a.slug}`} key={a.id} className="group grid grid-cols-[42px_1fr_auto] gap-3 py-5 border-b border-sage-light items-center"><span className="text-sage">0{i+1}</span><h3 className="font-serif text-xl sm:text-2xl group-hover:text-sage transition-colors">{a.title}</h3><ArrowRight className="w-4 h-4 transition-transform group-hover:translate-x-1"/></Link>)}</div></div></section>
 </div></div>
}
function EditorialSection({title,intro,items}:{title:string,intro:string,items:any[]}){if(!items.length)return null; return <section className="mb-28 grid lg:grid-cols-12 gap-10"><div className="lg:col-span-3"><span className="text-xs uppercase tracking-[.2em] text-slate">Explore topic</span><h2 className="font-serif text-4xl mt-2 mb-4">{title}</h2><p className="text-slate">{intro}</p></div><div className="lg:col-span-9 grid sm:grid-cols-2 lg:grid-cols-3 gap-6">{items.slice(0,3).map((a,i)=><Reveal key={a.id} delay={i*.05}><Link to={`/article/${a.slug}`} className="group block"><EditorialVisual kind={kindFor(a.category)} title={a.title} className="aspect-[4/3] rounded-[18px]"/><span className="text-xs uppercase tracking-[.18em] text-sage mt-5 block">{a.category} / {a.readTime}</span><h3 className="font-serif text-2xl mt-2 group-hover:text-sage transition-colors">{a.title}</h3></Link></Reveal>)}</div></section>}
function CompactList({title,items}:{title:string,items:any[]}){return <section><h2 className="font-serif text-3xl border-b border-sage-light pb-4 mb-2">{title}</h2>{items.map((a,i)=><Link to={`/article/${a.slug}`} key={a.id} className="group grid grid-cols-[90px_1fr] sm:grid-cols-[120px_1fr] gap-5 py-5 border-b border-sage-light"><EditorialVisual kind={kindFor(a.category)} title={a.title} className="aspect-square rounded-[14px]"/><div className="flex flex-col justify-center"><span className="text-xs uppercase tracking-widest text-sage">0{i+1} / {a.readTime}</span><h3 className="font-serif text-xl sm:text-2xl mt-2 group-hover:text-sage transition-colors">{a.title}</h3></div></Link>)}</section>}
